In [ ]:
import numpy as np
import pandas as pd

In [ ]:
employees_df = pd.read_excel('employees_data.xlsx')

##### Get all employees with salary > 50,000

In [ ]:
employees_df[employees_df['salary'] > 50000]

##### Show only name and department

In [45]:
employees_df[['name', 'department']]

    name department
0   Amit         IT
1   Riya         HR
2  Tarun         IT
3  Sneha         HR
4  Karan    Finance
5   Neha         IT
6  Arjun    Finance
7  Pooja         HR

##### Add a column salary_after_bonus = salary + 5000

In [ ]:
employees_df['salary_after_bonus'] = employees_df['salary'] + 5000

##### Replace missing salary with mean salary

In [ ]:
employees_df.fillna(employees_df['salary'].mean())

##### Find average salary per department

In [ ]:
department_group = employees_df.groupby('department')
department_group['salary'].mean()

##### Get top 3 highest paid employees

In [ ]:
employees_df.sort_values(by='salary', ascending=False).iloc[0:3]

In [ ]:
# Create a column:

# "High" if salary > 55000
# "Medium" if 45000–55000
# "Low" otherwise

In [ ]:
def salary_level_categorize(x: int):
  if x > 55000:
    return "high"
  elif 45000 <= x <= 55000:
    return "medium"
  else:
    return "low"

In [ ]:
employees_df['salary_level'] = employees_df['salary'].apply(salary_level_categorize)
employees_df

In [42]:
# Find employees:

# from IT department
# age < 30
# salary > 50000

In [49]:
it_df = employees_df[(employees_df['department'] == "IT") & (employees_df['age'] > 30)]
it_df[it_df['salary'] > 50000]

Empty DataFrame
Columns: [employee_id, name, department, salary, age, joining_date, salary_after_bonus, salary_level]
Index: []